#!/bin/bash


PPS1='\n
 ᴮᵒᵒᵉᵞ 



╼       

╭
───────────╮ WWW.BOOEYSAYS.COM\n			╭╼       ╾────────────╮ WWW.BOOEYSAYS.COM\n			

╭╼       ╾─╼SysOp╾@╼BooeySays.com╾─╮ WWW.BOOEYSAYS.COM\n			

╰╼ \w ╾							╰──────────────────────────
╭
╰
╭
─
╾
╾
       
╭
╼
       ╾─╼SysOp╾@───────────╮ WWW.BOOEYSAYS.COM\n			
────────────╮ WWW.BOOEYSAYS.COM\n			
╭

       

────────────╮ WWW.BOOEYSAYS.COM\n

 \w ───

